### ISSUE TITLE
Bug: SLF4J 1.8+ (recent) versions support

### ISSUE THREAD

**Issue by ivkomarov** [INFINITE-TECHNOLOGY/BOBBIN#20]
**The problem**: 

If we add some dependency with a transitive dependency to "org.slf4j:slf4j-api:1.8.0" and more recent, the Bobbin does not work

**Expected behavior**: 

<details>
<summary>Logs</summary>
<pre>
<code>
Bobbin          : main: Application working dir: /Users/%username%/Desktop/%project%
Bobbin          : main: Searching for Bobbin.yml in: ./Bobbin.yml (full path: /Users/%username%/Desktop/%project%/Bobbin.yml)
Bobbin          : main: Found: /Users/%username%/Desktop/%project%/Bobbin.yml
</code>
</pre>
</details>

**Actual behavior**: 

<details>
<summary>Logs</summary>
<pre>
<code>
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/%username%/Desktop/%project%/%project%/build/distributions/%project%-1.0.1/lib/bobbin-4.1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
</code>
</pre>
</details>

**Example Gradle configuration**: 

<details>
<summary>build.gradle</summary>
<pre>
<code>
def kotlin_version = '1.3.71'
def groovy_version = '2.5.4'
def bobbin_version = '4.1.0'
def textio_version = '3.4.1'
dependencies {
    implementation     "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation     "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"  
    implementation     "org.codehaus.groovy:groovy-all:$groovy_version" 
    implementation     "io.i-t:bobbin:$bobbin_version"  
    // the library below depends on a more recent slf4j artifact  
    implementation     "org.beryx:text-io:$textio_version"  
}
</code>
</pre>
</details>

Please, if you have any questions regarding configuration details, leave a comment and I will reply with more information on the problem.

**Comment by apryamostanov** [comment]
Hi @ivkomarov , will check and update ASAP.
Thank you for reporting the issue.

**Comment by apryamostanov** [comment]
Fixed, please kindly use the following dependency (note the package name is different):

`implementation 'io.i-t:bobbin-slf4j18:4.1.0'`

Let me know if there will be any issues or you will need support - I will be happy to help.
Thank you.
